# Generated by Django 4.2 on 2023-04-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empleado", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Empleado", new_name="EmpleadoDB",),
    ]
