# Generated by Django 4.2 on 2023-04-25 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departamento", "0002_alter_departamentodb_name_and_more"),
        ("empleado", "0002_rename_empleado_empleadodb"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleadodb",
            name="departamento",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="departamento.departamentodb",
            ),
        ),
        migrations.AddField(
            model_name="empleadodb",
            name="empleo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Contador"),
                    ("1", "Administrador"),
                    ("2", "Economista"),
                    ("3", "Otro"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="empleadodb",
            name="apellido",
            field=models.CharField(max_length=50, verbose_name="apellido"),
        ),
        migrations.AlterField(
            model_name="empleadodb",
            name="nombre",
            field=models.CharField(max_length=50, verbose_name="Nombre"),
        ),
    ]
