# Generated by Django 4.2 on 2023-05-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleado", "0004_habilidades_alter_empleadodb_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleadodb",
            name="habilidades",
            field=models.ManyToManyField(to="empleado.habilidades"),
        ),
    ]
