# Generated by Django 4.2 on 2023-05-17 02:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empleado", "0005_empleadodb_habilidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleadodb",
            name="hoja_vida",
            field=ckeditor.fields.RichTextField(default="texto"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="habilidades", unique_together={("habilidad",)},
        ),
    ]
