# Generated by Django 4.2 on 2023-05-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departamento", "0002_alter_departamentodb_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departamentodb",
            options={
                "ordering": ["-name"],
                "verbose_name": "Mi departamento",
                "verbose_name_plural": "Areas de la empresa",
            },
        ),
        migrations.AlterUniqueTogether(
            name="departamentodb", unique_together={("name", "short_name")},
        ),
    ]
